
list = ["jean.dupont.1.fr,
jean.dupont.2.fr,
jean.dupont.3.fr,
jean.dupont.4.fr,
jean.dupont.5.fr,
jean.dupont.6.fr,
jean.dupont.7.fr,
jean.dupont.8.fr,
jean.dupont.9.fr,
jean.dupont.10.fr,
jean.dupont.11.fr,
jean.dupont.12.fr,
jean.dupont.13.fr,
jean.dupont.14.fr,
jean.dupont.15.fr,
jean.dupont.16.fr,
jean.dupont.17.fr,
jean.dupont.18.fr,
jean.dupont.19.fr,
jean.dupont.20.fr,
jean.dupont.21.fr,
jean.dupont.22.fr,
jean.dupont.23.fr,
jean.dupont.24.fr,
jean.dupont.25.fr,
jean.dupont.26.fr,
jean.dupont.27.fr,
jean.dupont.28.fr,
jean.dupont.29.fr,
jean.dupont.30.fr,
jean.dupont.31.fr,
jean.dupont.32.fr,
jean.dupont.33.fr,
jean.dupont.34.fr,
jean.dupont.35.fr,
jean.dupont.36.fr,
jean.dupont.37.fr,
jean.dupont.38.fr,
jean.dupont.39.fr,
jean.dupont.40.fr,
jean.dupont.41.fr,
jean.dupont.42.fr,
jean.dupont.43.fr,
jean.dupont.44.fr,jean.dupont.45.fr,jean.dupont.46.fr,jean.dupont.47.fr,jean.dupont.48.fr,jean.dupont.49.fr,jean.dupont.50.fr"]

list.length.times do |i|
    case
    when i % 2 == 1
        puts list[i]
    end
end